#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep  5 15:16:46 2019

@author: maulik
"""

def prime(num):
   for i in range(2,num):
       if num % i ==0:
           #print("Not prime")
           return False
           break
   else:
       return True
       #print("prime")
       

def semiprime(N):
    for i in range(2, int(N**0.5)+1):
        if N%i==0:
            num1=int(i)
            #print(num1)
            num2= int(N/num1)
            #print(num2)
            if num1==num2:
                #print("Not a semiprime")
                return False
                break
            elif prime(num1) and prime(num2)==True:
                #print("The number is semiprime")
                return True
                break
    else:
        #print("Not a semiprime")
        return False
        
N1=int(input())
for i in range(2, N1-1):
    s1= i
    s2= N1-i
    if semiprime(s1) and semiprime(s2)== True:
        print("Yes")
        break
else:
    print("No")
    

        
